// Clearline sample data. Today = Sep 6, 2026.
export const tokens = {
  light: {
    background: "#f7f7f8",
    foreground: "#18181b",
    muted: "#efeff1",
    "muted-foreground": "#64687a",
    card: "#ffffff",
    "card-foreground": "#18181b",
    border: "#e4e4e7",
    primary: "#0f766e",
    "primary-foreground": "#ffffff",
    success: "#15803d",
    "success-foreground": "#ffffff",
    warning: "#b45309",
    "warning-foreground": "#ffffff",
    destructive: "#b91c1c",
    "destructive-foreground": "#ffffff",
    ring: "#0f766e",
    "chart-1": "#b3c2bf",
    "chart-2": "#8fd3c9",
    "chart-3": "#4fb8ab",
    "chart-4": "#2a9d90",
    "chart-5": "#0f766e",
    "chart-6": "#0b5049",
    radius: "6px",
  },
  dark: {
    background: "#141518",
    foreground: "#ececee",
    muted: "#24262b",
    "muted-foreground": "#9b9fa8",
    card: "#1c1d21",
    "card-foreground": "#ececee",
    border: "#2e3036",
    primary: "#2aa393",
    "primary-foreground": "#07201d",
    success: "#4ade80",
    "success-foreground": "#052e16",
    warning: "#fbbf24",
    "warning-foreground": "#1c1400",
    destructive: "#f87171",
    "destructive-foreground": "#2a0a0a",
    ring: "#2dd4bf",
    "chart-1": "#5b6664",
    "chart-2": "#3f8f85",
    "chart-3": "#4fb8ab",
    "chart-4": "#66cbbf",
    "chart-5": "#8fd3c9",
    "chart-6": "#b9e8e1",
    radius: "6px",
  },
};
export const tokenNames = Object.keys(tokens.light);

export const stages = [
  {
    key: "lead",
    label: "Lead",
    borrower: "Getting started",
    icon: "circle",
    chart: 1,
  },
  {
    key: "application",
    label: "Application",
    borrower: "Application received",
    icon: "fileText",
    chart: 2,
  },
  {
    key: "processing",
    label: "Processing",
    borrower: "Gathering your documents",
    icon: "loader",
    chart: 3,
  },
  {
    key: "underwriting",
    label: "Underwriting",
    borrower: "In underwriting review",
    icon: "search",
    chart: 4,
  },
  {
    key: "conditional_approval",
    label: "Conditional approval",
    borrower: "Conditionally approved",
    icon: "listChecks",
    chart: 5,
  },
  {
    key: "clear_to_close",
    label: "Clear to close",
    borrower: "Clear to close",
    icon: "check",
    chart: 6,
  },
];
export const terminalStages = [
  {
    key: "funded",
    label: "Funded",
    borrower: "Closed and funded",
    icon: "circleCheck",
    tone: "success",
  },
  {
    key: "withdrawn",
    label: "Withdrawn",
    borrower: "Application withdrawn",
    icon: "circleMinus",
    tone: "muted",
  },
  {
    key: "denied",
    label: "Denied",
    borrower: "Not approved",
    icon: "circleX",
    tone: "destructive",
  },
];

export const conditionStatuses = [
  {
    key: "requested",
    label: "Requested",
    borrower: "Needed",
    icon: "circle",
    tone: "muted",
  },
  {
    key: "received",
    label: "Received",
    borrower: "Received, under review",
    icon: "clock",
    tone: "warning",
  },
  {
    key: "cleared",
    label: "Cleared",
    borrower: "Accepted",
    icon: "circleCheck",
    tone: "success",
  },
  {
    key: "waived",
    label: "Waived",
    borrower: "No longer needed",
    icon: "circleMinus",
    tone: "muted",
  },
];
export const needsAnother = {
  label: "Needs another: pages are cut off",
  icon: "circleAlert",
  tone: "destructive",
};
export const reviewStatuses = [
  { key: "pending", label: "Pending", icon: "clock", tone: "warning" },
  { key: "accepted", label: "Accepted", icon: "circleCheck", tone: "success" },
  { key: "rejected", label: "Rejected", icon: "circleX", tone: "destructive" },
];
export const priorTo = ["before approval", "before docs", "before funding"];

export const money = (n) => "$" + n.toLocaleString("en-US");
export const moneyM = (n) =>
  "$" + (n / 1e6).toFixed(n % 1e6 === 0 ? 0 : 1) + "M";

export const staff = [
  {
    name: "Priya Nair",
    role: "Superadmin",
    email: "priya@example.com",
    loans: "—",
    lastActive: "Now",
    initials: "PN",
    self: true,
  },
  {
    name: "Alex Rivera",
    role: "Loan officer",
    email: "alex@example.com",
    loans: 6,
    lastActive: "12 min ago",
    initials: "AR",
    nmls: "NMLS 1234567",
    phone: "(512) 555-0134",
  },
  {
    name: "Jordan Lee",
    role: "Loan officer",
    email: "jordan@example.com",
    loans: 4,
    lastActive: "Yesterday",
    initials: "JL",
  },
  {
    name: "Morgan Ellis",
    role: "Loan officer",
    email: "morgan@example.com",
    loans: 3,
    lastActive: "Sep 4",
    initials: "ME",
  },
  {
    name: "Sam Okafor",
    role: "Processor",
    email: "sam@example.com",
    loans: 8,
    lastActive: "2 min ago",
    initials: "SO",
  },
  {
    name: "Riley Brooks",
    role: "Processor",
    email: "riley@example.com",
    loans: "—",
    lastActive: "Sep 1",
    initials: "RB",
  },
];
const lo = {
  alex: "Alex Rivera",
  jordan: "Jordan Lee",
  morgan: "Morgan Ellis",
};
const ini = (n) =>
  n
    .split(" ")
    .map((w) => w[0])
    .join("");

const raw = [
  [
    "Fischer",
    "3 Quarry Rd",
    "Boise",
    "ID",
    274000,
    "FHA",
    "Purchase",
    "lead",
    4,
    "morgan",
  ],
  [
    "Dubois",
    "14 Cedar Row",
    "Tucson",
    "AZ",
    312000,
    "FHA",
    "Purchase",
    "lead",
    2,
    "jordan",
  ],
  [
    "Haddad",
    "71 Elm St",
    "Columbus",
    "OH",
    560000,
    "Conventional",
    "Purchase",
    "lead",
    1,
    "alex",
  ],
  [
    "Alvarez",
    "640 Sunset Blvd",
    "Phoenix",
    "AZ",
    529900,
    "Conventional",
    "Purchase",
    "application",
    1,
    "alex",
  ],
  [
    "Larsen",
    "22 Pinecrest Dr",
    "Minneapolis",
    "MN",
    418000,
    "VA",
    "Purchase",
    "application",
    3,
    "jordan",
  ],
  [
    "Chen",
    "412 Maple Ave",
    "Austin",
    "TX",
    485000,
    "Conventional",
    "Purchase",
    "processing",
    6,
    "alex",
    "Oct 3",
    "Needs review",
  ],
  [
    "Brooks",
    "155 Lakeshore Ave",
    "Madison",
    "WI",
    445000,
    "Conventional",
    "Purchase",
    "processing",
    12,
    "alex",
    null,
    "Stalled",
  ],
  [
    "Kim",
    "9 Orchard St",
    "Raleigh",
    "NC",
    389000,
    "Conventional",
    "Purchase",
    "processing",
    3,
    "alex",
    "Sep 15",
    "Needs review",
  ],
  [
    "Okonkwo",
    "1901 Birch Ct",
    "Denver",
    "CO",
    398000,
    "VA",
    "Purchase",
    "conditional_approval",
    9,
    "jordan",
    null,
    "Stalled",
  ],
  [
    "Patel",
    "88 Harbor View Dr",
    "Tampa",
    "FL",
    612500,
    "FHA",
    "Purchase",
    "conditional_approval",
    3,
    "alex",
  ],
  [
    "Moreau",
    "5 Vineyard Ct",
    "Sacramento",
    "CA",
    702000,
    "Conventional",
    "Purchase",
    "conditional_approval",
    2,
    "morgan",
  ],
  [
    "Nguyen",
    "27 Willow Ln",
    "Portland",
    "OR",
    355000,
    "Conventional",
    "Refinance",
    "clear_to_close",
    2,
    "jordan",
    "Sep 19",
  ],
  [
    "Sato",
    "300 Bayfront Way",
    "San Diego",
    "CA",
    720000,
    "Conventional",
    "Purchase",
    "clear_to_close",
    1,
    "morgan",
    "Sep 12",
  ],
];
export const loans = raw.map((r) => ({
  name: r[0],
  street: r[1],
  city: r[2],
  state: r[3],
  cityState: r[2] + ", " + r[3],
  amount: r[4],
  amountFmt: money(r[4]),
  program: r[5],
  purpose: r[6],
  stage: r[7],
  stageLabel: stages.find((s) => s.key === r[7]).label,
  days: r[8],
  daysFmt: r[8] + " d",
  lo: lo[r[9]],
  loKey: r[9],
  loInitials: ini(lo[r[9]]),
  mine: r[9] === "alex",
  targetClose: r[10] || "—",
  tag: r[11] || null,
  tagIcon: r[11] === "Stalled" ? "flag" : r[11] ? "fileText" : null,
  processor:
    r[7] === "processing" ||
    r[7] === "conditional_approval" ||
    r[7] === "clear_to_close"
      ? "Sam Okafor"
      : "—",
}));

export const columns = (filter = "all") =>
  stages.map((s) => {
    const items = loans.filter(
      (l) => l.stage === s.key && (filter === "all" || l.mine),
    );
    return {
      ...s,
      items,
      count: items.length,
      total: money(items.reduce((a, l) => a + l.amount, 0)),
      empty: items.length === 0,
    };
  });

export const closedLoans = [
  {
    name: "Rivera",
    street: "18 Foxglove Ln",
    cityState: "El Paso, TX",
    amountFmt: "$410,000",
    program: "Conventional",
    purpose: "Purchase",
    stageLabel: "Funded",
    fundedOn: "Aug 28",
    lo: "Alex Rivera",
    loInitials: "AR",
  },
  {
    name: "Sandoval",
    street: "902 Prairie Ct",
    cityState: "Omaha, NE",
    amountFmt: "$352,000",
    program: "FHA",
    purpose: "Purchase",
    stageLabel: "Funded",
    fundedOn: "Sep 2",
    lo: "Jordan Lee",
    loInitials: "JL",
  },
];

export const mariaNeeds = [
  {
    title: "Government photo ID",
    instructions: "A driver's license or passport, front and back.",
    status: "cleared",
    borrower: "Accepted",
    tone: "success",
    icon: "circleCheck",
    priorTo: "before docs",
    age: "5 d",
    zone: "none",
  },
  {
    title: "Pay stubs, last 30 days",
    instructions: "Your two most recent pay stubs, all pages.",
    status: "requested",
    borrower: "Needs another: pages are cut off",
    tone: "destructive",
    icon: "circleAlert",
    priorTo: "before docs",
    age: "6 d",
    zone: "idle",
    rejected: true,
  },
  {
    title: "W-2s, last 2 years",
    instructions: "Your W-2 forms for 2024 and 2025.",
    status: "received",
    borrower: "Received, under review",
    tone: "warning",
    icon: "clock",
    priorTo: "before docs",
    age: "2 d",
    zone: "none",
    doc: {
      file: "w2-2025.pdf",
      via: "uploaded via Maria's link",
      age: "2 d ago",
      status: "Pending",
    },
  },
  {
    title: "Bank statements, last 2 months",
    instructions:
      "All pages of your checking and savings statements for July and August.",
    status: "requested",
    borrower: "Needed",
    tone: "muted",
    icon: "circle",
    priorTo: "before docs",
    age: "6 d",
    zone: "uploading",
  },
  {
    title: "Purchase contract",
    instructions: "The signed contract for 412 Maple Ave.",
    status: "cleared",
    borrower: "Accepted",
    tone: "success",
    icon: "circleCheck",
    priorTo: "before approval",
    age: "4 d",
    zone: "none",
  },
  {
    title: "Homeowners insurance binder",
    instructions:
      "Proof of insurance from your insurer, once you have chosen one.",
    status: "requested",
    borrower: "Needed",
    tone: "muted",
    icon: "circle",
    priorTo: "before funding",
    age: "6 d",
    zone: "idle",
  },
].map((c) => ({
  ...c,
  staffLabel: conditionStatuses.find((s) => s.key === c.status).label,
  staffIcon: conditionStatuses.find((s) => s.key === c.status).icon,
  staffTone: conditionStatuses.find((s) => s.key === c.status).tone,
}));

export const pendingDocs = [
  {
    file: "w2-2025.pdf",
    condition: "W-2s, last 2 years",
    loan: "Chen",
    via: "via Maria's link",
    age: "2 d",
  },
  {
    file: "bank-stmt-jul.pdf",
    condition: "Bank statements, last 2 months",
    loan: "Kim",
    via: "uploaded by Sam Okafor",
    age: "1 d",
  },
  {
    file: "contract-signed.pdf",
    condition: "Purchase contract",
    loan: "Brooks",
    via: "via link",
    age: "1 d",
  },
  {
    file: "paystubs-aug.pdf",
    condition: "Pay stubs, last 30 days",
    loan: "Kim",
    via: "via link",
    age: "6 h",
  },
  {
    file: "photo-id.jpg",
    condition: "Government photo ID",
    loan: "Okonkwo",
    via: "via link",
    age: "1 h",
  },
];

export const aging = [
  { bucket: "0–3 d", n: 9 },
  { bucket: "4–7 d", n: 7 },
  { bucket: "8–14 d", n: 5 },
  { bucket: "15+ d", n: 2 },
].map((b) => ({ ...b, pct: Math.round((b.n / 9) * 100) }));

export const attention = [
  {
    loan: "Brooks",
    street: "155 Lakeshore Ave",
    stage: "Processing",
    stageIcon: "loader",
    chart: 3,
    days: "12 d",
    target: "—",
    reason: "Stalled 12 d in Processing",
    tone: "warning",
    icon: "flag",
    mine: true,
  },
  {
    loan: "Okonkwo",
    street: "1901 Birch Ct",
    stage: "Conditional approval",
    stageIcon: "listChecks",
    chart: 5,
    days: "9 d",
    target: "—",
    reason: "Stalled 9 d in Conditional approval",
    tone: "warning",
    icon: "flag",
    mine: false,
  },
  {
    loan: "Kim",
    street: "9 Orchard St",
    stage: "Processing",
    stageIcon: "loader",
    chart: 3,
    days: "3 d",
    target: "Sep 15",
    reason: "Closing in 9 d, not yet clear to close",
    tone: "destructive",
    icon: "calendar",
    mine: true,
  },
];

export const loanActivity = [
  {
    text: "Priya Nair (viewing as Sam Okafor) rejected Pay stubs: pages are cut off",
    time: "2 min ago",
    icon: "circleX",
    tone: "destructive",
  },
  {
    text: "Sam Okafor accepted purchase-contract.pdf",
    time: "1 h ago",
    icon: "circleCheck",
    tone: "success",
  },
  {
    text: "Alex Rivera moved the loan from Application to Processing",
    time: "Yesterday",
    icon: "arrowRight",
    tone: "muted",
  },
  {
    text: "Maria Chen uploaded w2-2025.pdf",
    time: "2 d ago",
    icon: "upload",
    tone: "muted",
  },
  {
    text: "Maria Chen uploaded photo-id.jpg",
    time: "5 d ago",
    icon: "upload",
    tone: "muted",
  },
  {
    text: "Alex Rivera copied Maria's link",
    time: "6 d ago",
    icon: "link",
    tone: "muted",
  },
  {
    text: "Alex Rivera created the loan",
    time: "6 d ago",
    icon: "plus",
    tone: "muted",
  },
];

export const globalActivity = [
  {
    actor: "Priya Nair",
    action: "stopped viewing as Sam Okafor",
    loan: "—",
    time: "1 min ago",
    type: "Impersonation",
    icon: "eye",
  },
  {
    actor: "Priya Nair (viewing as Sam Okafor)",
    action: "rejected Pay stubs: pages are cut off",
    loan: "Chen",
    time: "2 min ago",
    type: "Documents",
    icon: "circleX",
  },
  {
    actor: "Priya Nair",
    action: "started viewing as Sam Okafor",
    loan: "—",
    time: "4 min ago",
    type: "Impersonation",
    icon: "eye",
  },
  {
    actor: "Maria Chen",
    action: "uploaded photo-id.jpg via the borrower link",
    loan: "Okonkwo",
    time: "1 h ago",
    type: "Documents",
    icon: "upload",
  },
  {
    actor: "Sam Okafor",
    action: "cleared Purchase contract",
    loan: "Sato",
    time: "3 h ago",
    type: "Conditions",
    icon: "circleCheck",
  },
  {
    actor: "Maria Chen",
    action: "uploaded paystubs-aug.pdf via the borrower link",
    loan: "Kim",
    time: "6 h ago",
    type: "Documents",
    icon: "upload",
  },
  {
    actor: "Alex Rivera",
    action: "moved the loan from Lead to Application",
    loan: "Alvarez",
    time: "Yesterday",
    type: "Stage changes",
    icon: "arrowRight",
  },
  {
    actor: "Alex Rivera",
    action: "moved the loan from Application to Processing",
    loan: "Chen",
    time: "Yesterday",
    type: "Stage changes",
    icon: "arrowRight",
  },
  {
    actor: "Priya Nair",
    action: "created user Riley Brooks · Processor",
    loan: "—",
    time: "Sep 1",
    type: "Users",
    icon: "users",
  },
  {
    actor: "System",
    action: "reset demo data",
    loan: "—",
    time: "Sep 1, 04:00",
    type: "Resets",
    icon: "rotateCcw",
  },
];
export const activityFilters = [
  "All",
  "Stage changes",
  "Documents",
  "Conditions",
  "Users",
  "Impersonation",
  "Resets",
];
